export type SecurityCharacteristicsFields = {
  id: string;
  SECDATE: string | Date;
  CID: string;
  TKRID: string;
  PRICE: number;
  MKTSECT: number;
  DIVYLD: number;
  ANNDIV: number;
  EXDIVDT: string | Date;
  DVDLT: number;
  EPS: number;
  EPSHIGH: number;
  EPSLOW: number;
  PE: number;
  PE1YR: number;
  EPSGRWTH: number;
  MKTCAP: number;
  VOLUME: number;
  LASTDIV: number;
  WKHI52: number;
  WKLO52: number;
  ROE: number;
  PBOOKVAL: number;
  BETA: number;
  PRCHGYTD: number;
  PRCASH: number;
  MATURITY: string | Date;
  ANNYLD: number;
  YLDTMAT: number;
  SPRATE: string;
  DURATION: number;
  INDUSTRY: string;
  USERDEF1: number;
  USERDEF2: number;
  USERDEF3: number;
  USERDEF4: number;
  USERDEF5: number;
  PEYTD: number;
  PRCHG1YR: number;
  BTR1000: number;
  BTR1000G: number;
  BTR1000V: number;
  BTR2000: number;
  BTR2000G: number;
  BTR2000V: number;
  BTR3000: number;
  BTR3000G: number;
  BTR3000V: number;
  BTRMID: number;
  BTRMIDG: number;
  BTRMIDV: number;
  BTMID: number;
  BTSPBGI: number;
  BTSPBVI: number;
  BTSPSCI: number;
  BTSPX: number;
  DIVYLD5Y: number;
  DIVGR5Y: number;
  DIVYLDIR: number;
  DIVPSANN: number;
  EPS10YGR: number;
  EPS3YGR: number;
  EPS5YGR: number;
  EPSCHGCF: number;
  EPSLTM: number;
  EPSLSTFY: number;
  EPSCOFTM: number;
  EPSCOCFY: number;
  EPSCONFY: number;
  EPSCLFY: number;
  EPSNCF: number;
  EPSNNFY: number;
  EPSLTFG: number;
  LTDTOTCP: number;
  MGNGROSS: number;
  MGNNP: number;
  MGNOPER: number;
  ROEQUITY: number;
  MKTCAP2: number;
  PEGRATIO: number;
  PEFWD: number;
  PECFY: number;
  PELTM: number;
  PE5YAVG: number;
  PSBOOK: number;
  PSCASHFL: number;
  PSREV: number;
  PSCFLTM: number;
  PSEBITMG: number;
  PB: number;
  PRCF: number;
  PRSALES: number;
  COUPON: number;
  CALLDATE: string | Date;
  CALLPRICE: number;
  PUTDATE: string | Date;
  PUTPRICE: number;
  RECDTYPE: string;
};


export const getSecurityCharacteristicsDefaultVal = {
  id: '',
  SECDATE: new Date(),
  CID: '',
  TKRID: '',
  PRICE: 0,
  MKTSECT: 0,
  DIVYLD: 0,
  ANNDIV: 0,
  EXDIVDT: new Date(),
  DVDLT: 0,
  EPS: 0,
  EPSHIGH: 0,
  EPSLOW: 0,
  PE: 0,
  PE1YR: 0,
  EPSGRWTH: 0,
  MKTCAP: 0,
  VOLUME: 0,
  LASTDIV: 0,
  WKHI52: 0,
  WKLO52: 0,
  ROE: 0,
  PBOOKVAL: 0,
  BETA: 0,
  PRCHGYTD: 0,
  PRCASH: 0,
  MATURITY: new Date(),
  ANNYLD: 0,
  YLDTMAT: 0,
  SPRATE: '',
  DURATION: 0,
  INDUSTRY: '',
  USERDEF1: 0,
  USERDEF2: 0,
  USERDEF3: 0,
  USERDEF4: 0,
  USERDEF5: 0,
  PEYTD: 0,
  PRCHG1YR: 0,
  BTR1000: 0,
  BTR1000G: 0,
  BTR1000V: 0,
  BTR2000: 0,
  BTR2000G: 0,
  BTR2000V: 0,
  BTR3000: 0,
  BTR3000G: 0,
  BTR3000V: 0,
  BTRMID: 0,
  BTRMIDG: 0,
  BTRMIDV: 0,
  BTMID: 0,
  BTSPBGI: 0,
  BTSPBVI: 0,
  BTSPSCI: 0,
  BTSPX: 0,
  DIVYLD5Y: 0,
  DIVGR5Y: 0,
  DIVYLDIR: 0,
  DIVPSANN: 0,
  EPS10YGR: 0,
  EPS3YGR: 0,
  EPS5YGR: 0,
  EPSCHGCF: 0,
  EPSLTM: 0,
  EPSLSTFY: 0,
  EPSCOFTM: 0,
  EPSCOCFY: 0,
  EPSCONFY: 0,
  EPSCLFY: 0,
  EPSNCF: 0,
  EPSNNFY: 0,
  EPSLTFG: 0,
  LTDTOTCP: 0,
  MGNGROSS: 0,
  MGNNP: 0,
  MGNOPER: 0,
  ROEQUITY: 0,
  MKTCAP2: 0,
  PEGRATIO: 0,
  PEFWD: 0,
  PECFY: 0,
  PELTM: 0,
  PE5YAVG: 0,
  PSBOOK: 0,
  PSCASHFL: 0,
  PSREV: 0,
  PSCFLTM: 0,
  PSEBITMG: 0,
  PB: 0,
  PRCF: 0,
  PRSALES: 0,
  COUPON: 0,
  CALLDATE: new Date(),
  CALLPRICE: 0,
  PUTDATE: new Date(),
  PUTPRICE: 0,
  RECDTYPE: ''
};
